# Mussel genomes assembly pipeline

import glob
import os.path
import re
import math
from snakemake.utils import min_version

min_version("5.27.4")

configfile: "config/config.yaml"

container: config['sif_tools']

include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/genomescope.smk"
include: "rules/supernova.smk"
include: "rules/purge_dups.smk"
include: "rules/busco.smk"
include: "rules/kat.smk"
include: "rules/stats.smk"
include: "rules/agouti.smk"
include: "rules/blobtoolkit.smk"
include: "rules/cleaning.smk"
include: "rules/mapping.smk"
include: "rules/asm_improvement.smk"
include: "rules/repeats.smk"
include: "rules/annotation.smk"

rule all_v6:
    input: 
        expand("results/preprocessing/{sample}/{sample}_S1_L001_R1_001.fastq.gz",
            sample=config['samples']),
        expand("results/genomescope/{sample}/genomescope_res_{sample}/{sample}_preproc_summary.txt",
            sample=config['samples']),
        expand("results/supernova_assemblies/{sample}_{version}/DONE",
            sample=config['samples'], version=["v1", "v2"]),
        expand("results/fasta/{sample}_{version}.pseudohap.fasta.gz",
            sample=config['samples'], version=["v3", "v6"]),
        expand("results/kat/{sample}_{version}/{sample}_{version}_spectra.pdf",
            sample=config['samples'], version=["v1", "v2", "v3", "v4", "v5", "v6"]),
        expand("results/blobtoolkit/DONE_{sample}_{version}",
            sample=config['samples'], version=['v5', 'v6']),
        expand("results/blobtoolkit/blobdirs/{sample}_v5_kept",
            sample=config['samples']),
        expand("results/mapping/{sample}_v6.bam",
            sample=config['samples']),
        expand("results/mapping/{sample}_v6.stats",
            sample=config['samples']),

rule asm_improvement:
    input:
        expand("results/fasta/{sample}_v7.pseudohap.fasta.gz",
            sample=config['samples']),
        expand("results/blobtoolkit/DONE_{sample}_v7",
            sample=config['samples']),
        expand("results/kat/{sample}_v7/{sample}_v7_spectra.pdf",
            sample=config['samples']),
        expand("results/mapping/{sample}_v7.bam",
            sample=config['samples']),
        expand("results/mapping/{sample}_v7.stats",
            sample=config['samples']),

rule stats:
    input:
        "results/stats/busco_summary.tsv",
        "results/supernova_assemblies/supernova_assemblies_stats.csv",
        "results/stats/assembly_stats.csv",

rule repeats:
    input:
        expand("results/repeats/{asm}.fa.masked",
            asm=['gallo_v7', 'edu_v7', 'tros_v7']),

rule annotation:
    input:
        expand("results/annotation/braker/{asm}/braker.gtf",
            asm=['gallo_v7', 'tros_v7', 'edu_v7'])
