# Mussel genomes assembly pipeline

import glob
import os.path
import re
from snakemake.utils import min_version

min_version("5.27.4")

configfile: "config/config.yaml"

container: config['sif_tools']

include: "rules/common.smk"

rule all:
    input: 
        expand("results/preprocessing/{sample}/{sample}_S1_L001_R1_001.fastq.gz",
            sample=config['samples']),
        expand("results/genomescope/{sample}/genomescope_res_{sample}/{sample}_preproc_summary.txt",
            sample=config['samples']),
        expand("results/supernova_assemblies/{sample}_{version}/DONE",
            sample=config['samples'], version=["v1", "v2"]),
        expand("results/fasta/{sample}_v3.pseudohap.fasta.gz",
            sample=config['samples'], version=["v3", "v4", "v5", "v6"]),
        expand("results/busco/{sample}_{version}_{db}/run_{db}/short_summary.txt",
            sample=config['samples'], version=["v1", "v2", "v3", "v4", "v5", "v6"],
            db=["metazoa_odb10", "mollusca_odb10"]),
        expand("results/busco/gallo_{ENA}_{db}/run_{db}/short_summary.txt",
            ENA=['LNJA01', 'UYE01'], db=["metazoa_odb10", "mollusca_odb10"]),
        expand("results/kat/{sample}_{version}/{sample}_{version}_spectra.pdf",
            sample=config['samples'], version=["v1", "v2", "v3", "v4", "v5", "v6"]),
        "results/supernova_assemblies/supernova_assemblies_stats.csv",
        "results/stats/assembly_stats.csv",
        expand("results/blobtoolkit/DONE_{sample}_{version}",
            sample=config['samples'], version=['v5', 'v6']),
        expand("results/blobtoolkit/blobdirs/{sample}_v5_kept",
            sample=config['samples']),


include: "rules/preprocessing.smk"
include: "rules/genomescope.smk"
include: "rules/supernova.smk"
include: "rules/purge_dups.smk"
include: "rules/busco.smk"
include: "rules/kat.smk"
include: "rules/stats.smk"
include: "rules/agouti.smk"
include: "rules/blobtoolkit.smk"
include: "rules/cleaning.smk"

