# Configuration file of the pipeline

sif_tools: containers/assembly_tools.sif
sif_supernova: containers/supernova.sif

raw_names:
  gallo: "Gallo_Med"
  edu: "EDU"
  tros: "TROS"
#  cancer_R8: "R8_repaired"

samples: ["gallo", "edu", "tros"]

supernova_mem: 400
