# Configuration file of the pipeline

sif_tools: containers/assembly_tools.sif
sif_supernova: containers/supernova.sif
dfam_container: docker://dfam/tetools:1.3.1

raw_names:
  gallo: "Gallo_Med"
  edu: "EDU"
  tros: "TROS"
#  bv: "BV"

samples:
  - gallo
  - edu
  - tros
#  - bv

published_assemblies:
  GCA017311375: "ftp://ftp.ncbi.nih.gov/genomes/genbank/invertebrate/Mytilus_coruscus/all_assembly_versions/GCA_017311375.1_Mcoruscus_HiC/GCA_017311375.1_Mcoruscus_HiC_genomic.fna.gz"
  GCA900618805: "ftp://ftp.ncbi.nih.gov/genomes/genbank/invertebrate/Mytilus_galloprovincialis/all_assembly_versions/GCA_900618805.1_MGAL_10/GCA_900618805.1_MGAL_10_genomic.fna.gz"

genomescope:
  kmc_mem: 100
  kmer_size: 21
  threads: 16

fastp_threads: 16

supernova_mem: 400
supernova_order:
  - gallo_v1
  - tros_v1
  - edu_v1
  - gallo_v2
  - tros_v2
  - edu_v2

purge_dups:
  threads: 16
  M: 20000
  E: 15000

busco:
  metazoa: https://busco-data.ezlab.org/v5/data/lineages/metazoa_odb10.2021-02-24.tar.gz
  mollusca: https://busco-data.ezlab.org/v5/data/lineages/mollusca_odb10.2020-08-05.tar.gz
  threads: 16

agouti:
  threads: 20

btk:
  threads: 32
  blobtools_path: /opt/blobtoolkit/blobtools2/blobtools # inside singularity image for v2.4.0

scaff_prefix:
  gallo: mg
  edu: me
  tros: mt
  bv: bv

mapping:
  threads: 32

asm_improvement:
  mtro_ont: resources/ont_reads/mtro_ont_reads.fastq.gz
  java_mem: 400
  max_concurrent_pilon: 2

repeats:
  threads: 16 # must be multiple of 4
  asm_db: ["gallo_v7", "tros_v7", "edu_v7", "GCA017311375", "GCA900618805"]

annotation:
  hisat2_threads: 10
  braker_threads: 16
  genemark_path: "/opt/gmes_linux_64" # inside assembly_tools.sif
  interproscan_path: "/opt/interproscan-5.51-85.0" # inside assembly_tools.sif
  interproscan_threads: 10