# Configuration file of the pipeline

sif_tools: containers/assembly_tools.sif
sif_supernova: containers/supernova.sif

raw_names:
  gallo: "Gallo_Med"
  edu: "EDU"
  tros: "TROS"
  bv: "BV"
  R8: "R8_repaired"

samples:
  - gallo
  - edu
  - tros
#  - bv
#  - R8

genomescope:
  kmc_mem: 100
  kmer_size: 21
  threads: 16

fastp_threads: 16

supernova_mem: 400
supernova_order:
  - gallo_v1
  - tros_v1
  - edu_v1
  - gallo_v2
  - tros_v2
  - edu_v2

purge_dups:
  threads: 16
  M: 20000
  E: 15000

busco:
  metazoa: https://busco-data.ezlab.org/v4/data/lineages/metazoa_odb10.2019-11-20.tar.gz
  mollusca: https://busco-data.ezlab.org/v4/data/lineages/mollusca_odb10.2019-11-20.tar.gz
  threads: 8

agouti:
  threads: 16

btk:
  threads: 16
