# Configuration file of the pipeline

sif_tools: containers/assembly_tools.sif
sif_supernova: containers/supernova.sif

raw_names:
  gallo: "Gallo_Med"
  edu: "EDU"
  tros: "TROS"
#  cancer_R8: "R8_repaired"

samples:
  - gallo
  - edu
  - tros

kmc_mem: 100
genomescope_kmer_size: 19

supernova_mem: 400
supernova_order:
  - gallo_v1
  - tros_v1
  - edu_v1
  - gallo_v2
  - tros_v2
  - edu_v2

busco:
  metazoa: https://busco-data.ezlab.org/v4/data/lineages/metazoa_odb10.2019-11-20.tar.gz
  mollusca: https://busco-data.ezlab.org/v4/data/lineages/mollusca_odb10.2019-11-20.tar.gz
