# Configuration file of the pipeline

sif_tools: containers/assembly_tools.sif
sif_supernova: containers/supernova.sif

raw_names:
  gallo: "Gallo_Med"
  edu: "EDU"
  tros: "TROS"
#  bv: "BV"

samples:
  - gallo
  - edu
  - tros
#  - bv

ENA_assemblies:
  LNJA01: "ftp://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/ln/LNJA01.fasta.gz"
  UYJE01: "ftp://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/uy/UYJE01.fasta.gz"

genomescope:
  kmc_mem: 100
  kmer_size: 21
  threads: 16

fastp_threads: 16

supernova_mem: 400
supernova_order:
  - gallo_v1
  - tros_v1
  - edu_v1
  - gallo_v2
  - tros_v2
  - edu_v2

purge_dups:
  threads: 16
  M: 20000
  E: 15000

busco:
  metazoa: https://busco-data.ezlab.org/v4/data/lineages/metazoa_odb10.2019-11-20.tar.gz
  mollusca: https://busco-data.ezlab.org/v4/data/lineages/mollusca_odb10.2019-11-20.tar.gz
  threads: 16

agouti:
  threads: 16

anvio:
  threads: 16

btk:
  threads: 32
  blobtools_path: /opt/blobtoolkit/blobtools2/blobtools # inside singularity image for v2.4.0

scaff_prefix:
  gallo: mg
  edu: me
  tros: mt
  bv: bv
